version: 1
default_environment: dev
send_anonymous_usage_stats: true
project_id: linkedin_sdk
plugins:
  extractors:
  - name: tap-linkedin
    namespace: tap_linkedin
    pip_url: -e .
    capabilities:
    - state
    - catalog
    - discover
    settings:
    - name: access_token
      kind: password
    - name: password
      kind: password
    - name: start_date
      value: '2010-01-01T00:00:00Z'
      kind: date_iso8601
    - name: end_date
      value: '2010-04-01T00:00:00Z'
      kind: date_iso8601
    config:
      client_secret: $TAP_LINKEDIN_CLIENT_SECRET
      access_token: $TAP_LINKEDIN_ACCESS_TOKEN
      refresh_token: $TAP_LINKEDIN_REFRESH_TOKEN
      accounts: $TAP_LINKEDIN_ACCOUNTS
      client_id: $TAP_LINKEDIN_CLIENT_ID
      user_agent: $TAP_LINKEDIN_USER_AGENT
      linkedin_version: '202207'
      x-restli-protocol-version: '1.0.0'
      content-type: 'text/plain'
  - name: Linkedin-Accounts
    inherit_from: tap-linkedin
    config:
      x-restli-protocol-version: 1.0.0
    select:
    - accounts
  - name: Linkedin-AdAccountsUsers
    inherit_from: tap-linkedin
    config:
      x-restli-protocol-version: 1.0.0
    select:
    - account_user
  - name: Linkedin-Creatives
    inherit_from: tap-linkedin
    config:
      x-restli-protocol-version: 2.0.0
    select:
    - creatives
  - name: Linkedin-Campaigns
    inherit_from: tap-linkedin
    config:
      x-restli-protocol-version: 1.0.0
    select:
    - campaign
  - name: Linkedin-CampaignGroups
    inherit_from: tap-linkedin
    config:
      x-restli-protocol-version: 1.0.0
    select:
    - campaign_groups
  - name: Linkedin-AdAnalyticsByCreative
    inherit_from: tap-linkedin
    config:
      x-restli-protocol-version: 1.0.0
    select:
    - ad_analytics_by_creative
  - name: Linkedin-AdAnalyticsByCampaign
    inherit_from: tap-linkedin
    config:
      x-restli-protocol-version: 1.0.0
    select:
    - ad_analytics_by_campaign
  - name: Linkedin-VideoAds
    inherit_from: tap-linkedin
    config:
      x-restli-protocol-version: 1.0.0
    select:
    - video_ads
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
  - name: target-csv
    variant: hotgluexyz
    pip_url: git+https://github.com/hotgluexyz/target-csv.git@0.3.3
    config:
      destination_path: /Users/neilgorman/Documents/GitHub/tap-linkedin-sdk/output
  - name: target-snowflake
    variant: transferwise
    pip_url: pipelinewise-target-snowflake
    config:
      batch_size: 5
environments:
- name: dev
  config:
    plugins:
      loaders:
      - name: target-csv
      - name: target-snowflake
        config:
          primary_key_required: false
- name: staging
- name: prod
